### ISSUE TITLE
Tests fail with py-vapid 1.5.0

### ISSUE THREAD

**Issue by tgurr** [web-push-libs/pywebpush#121]
Tests fail with py-vapid 1.5.0:

```
======================================================================
FAIL: test_as_curl (test_webpush.WebpushTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/var/tmp/paludis/build/dev-python-pywebpush-1.10.1/work/PYTHON_ABIS/2.7/pywebpush-1.10.1/pywebpush/tests/test_webpush.py", line 310, in test_as_curl
    ok_(s in result, "missing: {}".format(s))
AssertionError: missing: -H "authorization: vapid 
>>  raise AssertionError('missing: -H "authorization: vapid ')
    

======================================================================
FAIL: test_send_vapid (test_webpush.WebpushTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/var/tmp/paludis/build/dev-python-pywebpush-1.10.1/work/PYTHON_ABIS/2.7/pywebpush-1.10.1/pywebpush/tests/test_webpush.py", line 172, in test_send_vapid
    ok_('vapid' in pheaders.get('authorization'))
AssertionError: None
>>  raise AssertionError(None)
```

while they run fine with py-vapid 1.7.0, probably the dependency requirement should be updated to reflect that a more recent py-vapid is required.

**Comment by jrconlin** [comment]
Thanks! Finally got a chance to address that. New version is on pypi.
