### ISSUE TITLE
Request did not validate missing authorization header

### ISSUE THREAD

**Issue by SuperDoxin** [web-push-libs/pywebpush#81]
When trying to send a push message to a firefox endpoint I get this error no matter what I try:

```
Traceback (most recent call last):
  File "/Users/Lieuwe/projects/hydra/venv/lib/python3.5/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/Users/Lieuwe/projects/hydra/venv/lib/python3.5/site-packages/channels/sessions.py", line 78, in inner
    return func(*args, **kwargs)
  File "/Users/Lieuwe/projects/hydra/venv/lib/python3.5/site-packages/channels/auth.py", line 42, in inner
    return func(message, *args, **kwargs)
  File "/Users/Lieuwe/projects/wendchat/consumers.py", line 61, in ws_message
    getattr(message_handlers, cmd)(message, data)
  File "/Users/Lieuwe/projects/wendchat/message_handlers.py", line 142, in on_message
    send_push_message(target, "Hallo wereld!")
  File "/Users/Lieuwe/projects/wendchat/methods.py", line 123, in send_push_message
    vapid_claims=chat_settings.CHAT_VAPID_CLAIM
  File "/Users/Lieuwe/projects/hydra/venv/lib/python3.5/site-packages/pywebpush/__init__.py", line 370, in webpush
    result, result.text))
pywebpush.WebPushException: Push failed: <Response [401]>: {"code": 401, "errno": 109, "error": "Unauthorized", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate missing authorization header"}
```

I'm generating the vapid keys as follows:

```
vapid = Vapid()
vapid.generate_keys()
vapid.save_key('vapid.private.pem')
vapid.save_public_key(vapid.public.pem)
```

The client then returns a subscription like

```
{"endpoint":"https://updates.push.services.mozilla.com/wpush/v2/gAAAAABaJRho_CagHOmnZA_qWzmKYyHuKCLL5cWTgNPZ8kx9AN6eKoyTr-sQYxcfmLnx_ddeE3GhlCgvELYu4a8sFOAihmCf0PzF_uaVMcAmOr7z1O8RKk006sEnK0qOULpumVOkMWQB1y237gQodOl686nwVvfefYHnVh_rY73f_jh8pLod-iY","keys":{"auth":"ImHBySkqpnaySV_PUbGKzQ","p256dh":"BOghS7L240dUayNDc0NP8jI-iEqLBWFOqElCRJyWyLEDEezNYwtyobd5JUFPv536o_YiB_zUwT8RRJLYYZXRaAM"}}
```

And I send a push notification like this

```
webpush(
                json.loads(sub.info),
                message,
                vapid_private_key='vapid.private.pem',
                vapid_claims=CHAT_VAPID_CLAIM = {"sub": "mailto:<redacted>", 'aud': 'https://localhost:8000'}
            )
```

When dumping the sent request using the curl option I do see an authorization header, so I'm not sure  why the error is complaining about that header missing.

Any help would be greatly appreciated.

**Comment by jrconlin** [comment]
`aud` in the VAPID info is a bit confusing. 

It's the URL of the machine you're talking to, not your URL. (Yes, I screwed up on early versions of the docs because it's confusing). Unless you're trying to talk to a push server on your local machine, you probably want the host for the Push Service (e.g. 'https://push.services.mozilla.org' for Firefox Push requests.) The good news is that the pywebpush lib will supply the value for you. 

Try the VAPID claims without the 'aud' and see if things work.

**Comment by SuperDoxin** [comment]
Ah thanks! That's pretty unintuitive.
